{
    'name': 'Report Stock',
    'category': 'Inventory',
    'description': 'Module Advance Report',
    "depends": ["stock", "purchase", "sale_management"],
    "data": ["security/ir.model.access.csv",
             "report/aging_report_views.xml",
             "report/fsn_report_views.xml",
             "report/xyz_report_views.xml",
             "report/fsn_xyz_report_views.xml",
             "report/out_of_stock_report_views.xml",
             "report/over_stock_report_views.xml",
             "report/age_breakdown_report_views.xml",
             "report/stock_movement_report_views.xml",
             "wizard/inventory_aging_report_views.xml",
             "wizard/inventory_aging_data_report_views.xml",
             "wizard/inventory_fsn_report_views.xml",
             "wizard/inventory_fsn_data_report_views.xml",
             "wizard/inventory_xyz_report_views.xml",
             "wizard/inventory_xyz_data_report_views.xml",
             "wizard/inventory_fsn_xyz_report_views.xml",
             "wizard/inventory_fsn_xyz_data_report_views.xml",
             "wizard/inventory_out_of_stock_report_views.xml",
             "wizard/inventory_out_of_stock_data_report_views.xml",
             "wizard/inventory_age_breakdown_report_views.xml",
             "wizard/inventory_over_stock_report_views.xml",
             "wizard/inventory_over_stock_data_report_views.xml",
             "wizard/inventory_stock_movement_report_views.xml",
             ],
    # 'assets': {
    #     'web.assets_backend': [
    #         'inventory_advanced_reports/static/src/js/action_manager.js']
    # },
    'installable': True,
    'auto_install': False,
    'application': True,
}
